### Admin
POST http://localhost:5216/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "maija1234@mail.com",
    "password": "12345"
}

### Admin
POST http://localhost:5216/api/v1/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2Y2JhNmY0ZS0yYWJmLTQ0MDMtYWUyMi1lNThkMmZkY2QxNTgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzNEBtYWlsLmNvbSIsIm5iZiI6MTcwMzMxMDUxOCwiZXhwIjoxNzAzNDgzMzE4LCJpYXQiOjE3MDMzMTA1MTgsImlzcyI6IkFiaGlzaGVrIiwiYXVkIjoiQWJoaXNoZWtFQ29tbWVyY2UifQ.ap2Bio5kSsJbaRCYDSmsWNGr4nOVCO3iRMIZoKp0ORc

{
  "name": "Cloths",
  "imageUrl": "https://placeimg.com/640/480/any?r=0.591926261873231"
}

### Admin
GET http://localhost:5216/api/v1/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhZmQyZjlhZS1iMjk1LTRkNjQtYTYzNC0yM2I4YWJlM2U3ZTUiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzNEBtYWlsLmNvbSIsIm5iZiI6MTcwMzE2NDE5MCwiZXhwIjoxNzAzMzM2OTkwLCJpYXQiOjE3MDMxNjQxOTAsImlzcyI6IkFiaGlzaGVrIiwiYXVkIjoiQWJoaXNoZWtFQ29tbWVyY2UifQ.F_YkM0K0tSR8wV4V7QMJ10EorrbBkx0VEkiBWH6DLzs

###
GET http://localhost:5216/api/v1/categories/{f13a62c7-52e5-468a-92b3-0fcb7a2dc19a} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2N2QyYTBjZC04Mjc0LTQyMDUtYjNlOS1jNjk4MDYxMzQ3OTAiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzMDFAbWFpbC5jb20iLCJuYmYiOjE3MDMwOTUyNTYsImV4cCI6MTcwMzI2ODA1NiwiaWF0IjoxNzAzMDk1MjU2LCJpc3MiOiJBYmhpc2hlayIsImF1ZCI6IkFiaGlzaGVrRUNvbW1lcmNlIn0.65k0Ij6UFG5Hn_Hf1Jcw-CaV9zbbti9f_sBwMxMenqM

###
PATCH  http://localhost:5216/api/v1/categories/{cc78ec60-68c8-43ae-9843-5e5466d44812} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0YzFmODU4ZS1lNDRlLTRjZDYtOWMwZi01YzVlOGU5Y2U2OWQiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM0MDgyMjAsImV4cCI6MTcwMzU4MTAyMCwiaWF0IjoxNzAzNDA4MjIwLCJpc3MiOiJBYmhpc2hlayIsImF1ZCI6IkFiaGlzaGVrRUNvbW1lcmNlIn0.8ARFxZDdo4Oi0i5Ml0GutLUx518FTAPDv7fhaxw867g

{
  "name": "Others",
  "imageUrl": "https://i.imgur.com/QkIa5tT.jpeg"
}

###
DELETE http://localhost:5216/api/v1/categories/{f13a62c7-52e5-468a-92b3-0fcb7a2dc19a} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2N2QyYTBjZC04Mjc0LTQyMDUtYjNlOS1jNjk4MDYxMzQ3OTAiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzMDFAbWFpbC5jb20iLCJuYmYiOjE3MDMwOTUyNTYsImV4cCI6MTcwMzI2ODA1NiwiaWF0IjoxNzAzMDk1MjU2LCJpc3MiOiJBYmhpc2hlayIsImF1ZCI6IkFiaGlzaGVrRUNvbW1lcmNlIn0.65k0Ij6UFG5Hn_Hf1Jcw-CaV9zbbti9f_sBwMxMenqM