### login admin
POST http://localhost:5216/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "maija1234@mail.com",
    "password": "12345"
}

### Anonymous
POST http://localhost:5216/api/v1/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmMWVkN2MwNi04NGRiLTRmY2EtYjI5OS0wYWQ3YWE4ZWQ2NDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM0OTY5MzMsImV4cCI6MTcwMzY2OTczMywiaWF0IjoxNzAzNDk2OTMzLCJpc3MiOiJBYmhpc2hlayIsImF1ZCI6IkFiaGlzaGVrRUNvbW1lcmNlIn0.LRRatYF8RIZ6O5fswGM3DIbtOOeZiX6-ZVO4o0V5IEk

{
  "title": "Product123",
  "description": "Product1 are designed to keeping in...",
  "price": 400,
  "inventory": 20,
  "images": [
    {
      "imageUrl": "https://placeimg.com/640/480/any?r=0.8807778235430017"
    },
    {
      "imageUrl":"https://placeimg.com/640/480/any?r=0.9300320592588625"
    }
  ],
  "categoryId": "00ff8bf6-192f-455b-a8cd-14ab4d81f7bc"
}

###
GET http://localhost:5216/api/v1/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5216/api/v1/products?Id=08b76f82-87bf-4bea-9de7-d2725dfb05cf HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5216/api/v1/products/{4e7b97fd-1ffb-46b0-9dc6-602cadb43aca} HTTP/1.1
Content-Type: application/json


###
Patch http://localhost:5216/api/v1/products/{4e7b97fd-1ffb-46b0-9dc6-602cadb43aca} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyZDkyOTM2OC02MjA4LTQyYzEtODhmMy1mMGE3MGExMTMyNmEiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzNEBtYWlsLmNvbSIsIm5iZiI6MTcwMzI1MzYyNywiZXhwIjoxNzAzNDI2NDI3LCJpYXQiOjE3MDMyNTM2MjcsImlzcyI6IkFiaGlzaGVrIiwiYXVkIjoiQWJoaXNoZWtFQ29tbWVyY2UifQ.xZkmfSSHdzQeO6nNSjr-oZmN-RloASTVjcauEaEnI6E

{
  "title": "Fresh Table1230",
  "description": "Andbooady cloths are designed to keeping in...",
  "price": 400,
  "inventory": 20,
  "categoryId": "71a9a2eb-9b16-4dde-b4c8-a05c9e3b3df4"
}

###
DELETE  http://localhost:5216/api/v1/products/{5f5d67fc-4fc7-4980-a804-0de787f2c7bd} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5NjFjNDM2MS1hNTQzLTQyZTUtOWE3ZS02N2JlMTVmZjZmMzgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6Im1haWphMTIzNEBtYWlsLmNvbSIsIm5iZiI6MTcwMzE3OTA0NiwiZXhwIjoxNzAzMzUxODQ2LCJpYXQiOjE3MDMxNzkwNDYsImlzcyI6IkFiaGlzaGVrIiwiYXVkIjoiQWJoaXNoZWtFQ29tbWVyY2UifQ.KE622jVAKxtF3NcB3pfYaQeLX1MZ9arar_40OiApqZ0


 